apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediasoup-edge
  labels:
    app: mediasoup-edge
  namespace: qos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediasoup-edge
  template:
    metadata:
      labels:
        app: mediasoup-edge
    spec:
      # Multiple SFU replicas run on the same edge node.
      hostNetwork: false
      dnsPolicy: ClusterFirst

      nodeSelector:
        role: edge

      # private GHCR이면 주석 해제
      imagePullSecrets:
      - name: regcred

      securityContext:
        seccompProfile:
          type: Localhost
          localhostProfile: allow-io-uring.json
    ## mediasoup-certs라는 Secret에 들어있는 파일들을 certs라는 볼륨 이름으로 쓰겠다
      volumes:
      - name: certs
        hostPath:
          path: /home/n2sl/yeon/qos/network/mediasoup-demo/server/certs
          type: Directory

      containers:
      - name: mediasoup-server
        image: ghcr.io/ahnyeohn/mediasoup-server-edge:v2
        imagePullPolicy: Always
        resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 400m
              memory: 200Mi
        env:
        - name: NODE_ENV
          value: "production"
        - name: DEBUG
          value: "mediasoup*"
        - name: SERVER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - name: signaling
          containerPort: 4443
          protocol: TCP
        - name: pipeapi
          containerPort: 4445
          protocol: TCP
        volumeMounts:
        - name: certs
          mountPath: /work/mediasoup-demo/server/certs
          readOnly: true

      - name: mediasoup-app
        image: ghcr.io/ahnyeohn/mediasoup-app-edge:v2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - name: web
          containerPort: 5555
          protocol: TCP
        volumeMounts:
        - name: certs
          mountPath: /work/mediasoup-demo/server/certs
          readOnly: true